version: '3.6'
services:
  sequelizemysql:
    build: ./sequelizemysql
    image: sequelizemysql
    container_name: sequelizemysql
    restart: always
    ports:
            - "3001:3001"
    depends_on:
      - mysql
    environment:
      - MYSQLHOST=mysql

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=toto
      - MYSQL_DATABASE=testapp
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3308:3306"

  admin:
    image: adminer
    ports:
      - "8080:8080"
